spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e2aaec24653e9049ceded19718ba137b
            redirect-uri: "http://localhost:3000/oauth2/callback/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          naver:
            client-id: UT1QczlOObzBDmYoN1V7
            client-secret: ZX_b3EL4h4
            redirect-uri: "http://localhost:3000/oauth2/callback/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

